### PR TITLE
Fix minor stuff (and add dialyxir to CI)

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Adds `dialyxir` to CI, fixes Dialyzer -issued warnings, and compile-time warnings.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
@odo, hi. Is this lib. still maintained? Any chance this pull request gets reviewed? Many thanks.

**Comment by paulo-ferraz-oliveira** [comment]
(not sure if the lib. is still maintained). @odo, bump! 😄 Thanks.

**Comment by odo** [comment]
Hi and thanks for contributing! I have no write access to this repo anymore (account of former employer).
But Im am happy to merge PRs on my fork at https://github.com/odo/eflatbuffers/

**Comment by paulo-ferraz-oliveira** [comment]
Is this repository no longer maintained? Do you know of a more recent FlatBuffers/Elixir library? I mean, I could also pull request to your, but then we'd have to change some other stuff to pull from the correct repo 😄

**Comment by paulo-ferraz-oliveira** [comment]
Hm... it seems the Hex.pm package is owned and published by you. So if I pull request there are you able to publish to Hex.pm?

**Comment by paulo-ferraz-oliveira** [comment]
Pull requested at [odo/eflatbuffers#1](https://github.com/odo/eflatbuffers/pull/1). Closing this one. Thanks...

**Pull request closed without merging**
